In [ ]:
# 建立文件夹
import os
 
cur_dir = 'F:/data_company'
folder_name = '百度'
if os.path.isdir(cur_dir): #使用了os.path.isdir函数判断已有文件夹的路径是否正确。
    os.mkdir(os.path.join(cur_dir, folder_name)) 
    #新的文件夹的路径可以由os.path.join函数，将已有文件夹的路径和新建文件夹文件名连接起来得到。
    #由于Windows操作系统和Linux操作系统，路径的连接符不同，使用os.path.join连接能够确保同时在不同的操作系统中正常工作。
else:
    print('建立文件夹的路径不存在')

In [3]:
#相同长度列表合并为字典
a = ['a','b','c']
b = [1,2,3]
x = dict(zip(a,b))
x

{'a': 1, 'b': 2, 'c': 3}

In [ ]:
# 固定长度列表切片
get_row = [原始列表]
data_final = [get_row[i:i+3] for i in range(0,len(get_row),3)] # 每3个一切割，少于3个有多少算多少

In [ ]:
#解码到中文的格式
text = b'8e9fc618fbd41e28' 
text_ = '8e9fc618fbd41e28'
t = text.decode('unicode_escape') #当原始数据为byte型时的解码
t2 = text_.encode('latin-1').decode('unicode_escape') #当原始数据为str型时的解码
print(t2)

In [ ]:
#selenium选项卡切换顺序
browser.switch_to_window(browser.window_handles[-1])#这是第二个选项卡
#顺序是0，-1,1...注意是类似index那种固定的顺序，和当前位置无关

In [ ]:
#selenium小操作
from selenium.webdriver import ActionChains

browser.execute_script("window.scrollBy(10000,0)") #向右横滚1000像素
actions = ActionChains(browser)
browser.actions.move_to_element_with_offset(form_need, x, y).perform() #在form_need上移动指针，x向→移动为正，y向↓移动为正
browser.execute_script("window.scrollBy(0,1000)") #整体页面向下滚动1000像素
browser.execute_script("window.scrollTo(0, document.body.scrollHeight)") #整体页面滚到底

In [ ]:
# selenium模式设置

CHROME_OPTIONS = webdriver.ChromeOptions()
#CHROME_OPTIONS.binary_location = "C:/Program Files (x86)/Google/Chrome/Application/chrome.exe" #chrome浏览器所在路径
CHROME_OPTIONS.add_argument('headless')

#PhantomJS模式运行
#browser = webdriver.PhantomJS()

#headless模式运行
browser = webdriver.Chrome(chrome_options=CHROME_OPTIONS)

#实体模式
#browser = webdriver.Chrome()

In [2]:
#字符串替换操作
data_need = data_need.translate(str.maketrans('', '', '</em>'))
#前两个是长度相同的替换，默认没第三个，第三个参数是直接将''其中的内容替换为None
#特别注意，替换为空是，''内包含的单个(不在一起的)字符也会被替换

#例子：注意字符c的变化
a = 'adcsdfasfcccffasdg'
b = a.translate(str.maketrans('', '', 'ccc')) #只要有c就替掉
c = a.replace('ccc','')  #只有ccc在一起才替掉
print(b)
print(c)

adsdfasfffasdg
adcsdfasfffasdg


In [ ]:
#以下是链式替换
for index in df.index:
    df.loc[index, '日期'] = df.loc[index, '日期'].replace('年','-').replace('月','-').replace('日','')

In [8]:
#keras的按轴合并矩阵或层

from keras import backend as K

t1 = K.variable(np.array([[[1, 2],[2,3]],[[4,4], [5,3]]]))
t2 = K.variable(np.array([[[7, 4],[8,4]],[[2,10],[15,11]]]))
 
d0 = K.concatenate([t1,t2], axis=0) #按t1[0],t2[0]轴，即[[1, 2],[2,3]],[[4,4], [5,3]] + [[7, 4],[8,4]],[[2,10],[15,11]]，再合到一起括起来
d1 = K.concatenate([t1,t2], axis=1) #按t1[0][0],t2[0][0]轴，即[1, 2],[2,3]+ [7, 4],[8,4] 扩一下 + [4,4], [5,3] + [2,10],[15,11]扩一下，最后总括
d2 = K.concatenate([t1,t2], axis=2) #按t1[0][0][0],t2[0][0][0]轴，即1, 2 + 7,4扩一下 + 2,3 + 8,4扩一下，总外扩一下，+4,4+2,10扩一下+。。。+最后总括
d3 = K.concatenate([t1,t2], axis=-1) #按最后一个轴，和上一行一样

print('d0:',K.eval(d0),'\nd1:',K.eval(d1),'\nd2:',K.eval(d2),'\nd3:',K.eval(d3))

Using TensorFlow backend.


d0: [[[ 1.  2.]
  [ 2.  3.]]

 [[ 4.  4.]
  [ 5.  3.]]

 [[ 7.  4.]
  [ 8.  4.]]

 [[ 2. 10.]
  [15. 11.]]] 
d1: [[[ 1.  2.]
  [ 2.  3.]
  [ 7.  4.]
  [ 8.  4.]]

 [[ 4.  4.]
  [ 5.  3.]
  [ 2. 10.]
  [15. 11.]]] 
d2: [[[ 1.  2.  7.  4.]
  [ 2.  3.  8.  4.]]

 [[ 4.  4.  2. 10.]
  [ 5.  3. 15. 11.]]] 
d3: [[[ 1.  2.  7.  4.]
  [ 2.  3.  8.  4.]]

 [[ 4.  4.  2. 10.]
  [ 5.  3. 15. 11.]]]


In [ ]:
#利用keras，numpy等进行线性代数的相关计算
from keras import backend as K
import numpy as np

a = K.flatten(np.array([[1,2],[3,4],[5,6]]))
b = K.flatten(np.array([[4,2,1],[3,7,2]]))
print(b)
v = K.variable(value=b, dtype='int32')
print(v)
ev = K.eval(v)
print(ev)

c = K.sum(a*b) #这里是一一对应相乘，其实就是向量的乘法。c等于ab两向量对应相乘再相加
print(K.eval(c))


from keras.layers import Add, Multiply

t1 = K.variable(np.array([[1,2],[3,4],[5,6]]), dtype='int32')
t2 = K.variable(np.array([[1,2],[3,4],[5,7]]), dtype='int32')
#t2 = K.variable(np.array([[4,2,1],[3,7,2]]), dtype='int32')
add = Add()([t1,t2])
mul = Multiply()([t1,t2]) #只能对应相乘，并非矩阵乘法
print('add：',K.eval(add),'multi：',K.eval(mul))

#矩阵乘法
np.dot(np.array([[1,2],[3,4],[5,7]]), np.array([[4,2,1],[3,7,2]]))

In [7]:
#numpy条件筛选
import numpy as np
l = np.array([1,2,3,4])
#np.where(condition, x, y) #满足条件(condition)，输出x，不满足输出y。
#np.where(condition) #只有条件 (condition)，没有x和y，则输出找到n维数组中特定数值的索引
np.where(l>2)[0] #注意要加0以便选取出供之后使用

array([2, 3], dtype=int64)

In [ ]:
#pandas读取中文路径报错
import pandas as pd

#下面直接读取含中文的文件名（或者中文路径）会报错
df = pd.read_csv(r"F:\wechat_public\亚可的小天地\亚可的小天地.csv")
#如果这样处理，就不会再报错：
f= open(r"F:\wechat_public\亚可的小天地\亚可的小天地.csv")
df= pd.read_csv(f)

In [ ]:
#loc和iloc区别
print(filtered_sub_df_binary.loc[4,'ImageId']) #按index取值
print(filtered_sub_df_binary['ImageId'].iloc[4])#按行号取值

In [ ]:
#dataframe转换成向量array格式
df_array = df.values
df_array

In [ ]:
#dataframe删除行df
df.drop(df.index[[16,17]],axis=0,inplace=True) #此时原数据结构改变，inplace=False时，原数据不改变，需赋值到新数据

In [ ]:
#dataframe删除列
df.drop(['B','C'],axis=1,inplace=True) #axis=1（按列方向操作）、inplace=True（修改完数据，在原数据上保存）

In [3]:
#构造dataframe方法,按行
import pandas as pd
ds2 = [[1,2],[3,4],[5,6]]
df2 = pd.DataFrame(ds2,columns=['a','b'])
df2

a  b
0  1  2
1  3  4
2  5  6

In [ ]:
#构造dataframe方法,按列
df = pd.DataFrame({'A':['A0', 'A1', 'A2', 'A3'],
                   'B':['B0', 'B1', 'B2', 'B3'],
                   'C':['C0', 'C1', 'C2', 'C3'],
                   'D':['D0', 'D1', 'D2', 'D3']}, index=list('5678'))

In [ ]:
#pandas去重复行
import pandas

f= open(r"F:\wechat_public\亚可的小天地\亚可的小天地.csv")
data = pandas.read_csv(f)
newdata = data.drop_duplicates(subset=['标题','链接'],keep='last') #注意要重新赋值，否则不会在原data上做出改变
#当keep=False时，就是去掉所有的重复行
#当keep=‘first'时，就是保留第一次出现的重复行
#当keep='last'时就是保留最后一次出现的重复行。（注意，这里的参数是字符串）】
newdata2 = data.drop_duplicates(subset=['标题'],keep='last') #此时只要标题一样就算重复

In [ ]:
#pandas升/降序方法
df_count.sort_values('dbscan_code',ascending= False) #ascending表示排序方法，True表示升序，False表示降序

In [ ]:
#pandas筛选指定条件
#找出每一种职业的平均年龄，并按照平均年龄从大到小排序
df.groupby("workclass").mean().sort_values(ascending=False)

In [ ]:
#pandas不使用.loc方法取值
dataframe[b][dataframe[a]==1].values[0] #在一行中a列等于1时b列的值

In [ ]:
#dataframe返回index值
a = df[df['q_id']=='2abdc94b3d8f15aa7ed4faae599f87a8'].index.tolist()[0]

In [ ]:
#dataframe打乱随机重新排列行

df_shuffle = df_need.sample(frac=1).reset_index(drop=True) #后半部分是对打乱后的index进行重排

In [7]:
#pymysql直接用数据库取值
import pymysql

connection = pymysql.connect(host = '47.92.25.70',user = 'root',password = 'Wfn031641',db = 'cxd_data',charset = 'utf8')
with connection.cursor() as cursor: 
    sql = "select * from `hcb_factory_price_key` where `factory` = '昌邑石化（江阴油库）'"
    cursor.execute(sql)
    r_id = cursor.fetchone()#此时格式是（id,name,type,time） 使用列表操作取得数据
print(r_id)

(2054, '昌邑石化（江阴油库）', '0# 车柴 国VI', datetime.datetime(2018, 10, 22, 16, 24, 19))


In [ ]:
#pandas左右合并操作
df_result = pandas.merge(df_left, df_right, how='left', on='date') #how参数默认是inner，即inner join，on参数是公共列，必须列名一致

In [ ]:
#pandas上下合并操作
import pandas as pd

df = pd.DataFrame({'A':['A0', 'A1', 'A2', 'A3'],
                   'B':['B0', 'B1', 'B2', 'B3'],
                   'C':['C0', 'C1', 'C2', 'C3'],
                   'D':['D0', 'D1', 'D2', 'D3']})

df2 = df.append(df, ignore_index=True) #自动续index
df3 = df2.append(df, ignore_index=True)
df3

In [ ]:
#pandas更改列名
df.columns = ['a','b','c'] #必须所有列名全写
df.rename(columns={'A':'a', 'B':'b', 'C':'c'}, inplace = True) #只需修改需要改的列名即可

In [ ]:
#pandas 新增(空)列
pandas.concat([df_contract, pandas.DataFrame(columns=['92_p','95_p','0_p'])]) #随机位置
df['D'] = None #最后增加单列

In [ ]:
#pandas存储时，去掉默认的第一列
df_contract.to_csv('E:/test.csv', mode = 'w', sep =',', index=False)

In [ ]:
#pandas将两个df存到同个excel的两个sheet里
writer=pandas.ExcelWriter('E:/20180927.xls')
df_up = pandas.read_sql(sql_up %c_name,connection)
df_down = pandas.read_sql(sql_down %c_name,connection)
df_up.to_excel(writer, sheet_name='Sheet1') 
df_down.to_excel(writer, sheet_name='Sheet2')
writer.save() #注意这行不能省

In [ ]:
#dataframe选取多个特定index的值
df_s = df.loc[[0,2]]

In [ ]:
#pandas按条件新建（替换）表格值方法
df_com = df_com[df_com['name'].str.contains('石化&石油')] #含有某字符的串筛选
df_v = df_com[~df_com['name'].str.contains('石化|石油|能源')]#去掉某字符串的筛选
sub_df['ImageId'] = sub_df['ImageId_ClassId'].apply(lambda x: x.split('_')[0]) #将ImageId_ClassId列的值按'_'分割并取第一个单独新建列
df_up['single_sum'] = df_up['Sl'] * df_up['Dj'] #计算两列的运算赋值到新列
train_nan_df['allMissing'] = (train_nan_df['Missing_defect'] == 4).astype(int) #如果Missing_defect列的值=4，新建的allMissing列值等于1

In [ ]:
#判断某个单元格是否为nan
import numpy as np

p = df.loc[0,'phone']
np.isnan(p) #返回True则为nan

In [ ]:
#处理nan值：将是否为nan的状态新加一列说明
#将有nan值的列做判断并单独新加一列并取反，因为有空值的时候返回为true，取反为false
#注意这里是pandas的特殊取反，其他python里不一样
train_df['新列名'] = ~train_df['有空值的列名'].isna() #~是取反符号，在其他情况下二进制专用，对于十进制数等于-x-1
train_df.head()

In [ ]:
#统一处理某列的nan值并替换
df['EncodedPixels'].fillna('',inplace=True) #注意inplace要设置成true才能替换

In [ ]:
#单独选择有空列的值，其中close_val_yesd是列名，如果列名写成value，则会选择所有有空值的列，会有重复行
df_p[df_p.isnull().close_val_yesd==True]
df[df['close_val_yesd'].notnull()] #这是选取close_val_yesd列值非空时所有行

In [ ]:
#将dataframe格式转换为list
import pandas as pd
import numpy as np
df= pd.read_excel(r'C://Users//Administrator//Desktop//jobDate.xls',encoding='UTF-8',header=0)#datafram格式
dataSet=np.array(df)#dataframe转numpy.array
dataSet=dataSet.tolist()#numpy.array转list

In [ ]:
#画图显示中文

plt.rcParams['font.sans-serif'] = ['SimHei'] # 步骤一（替换sans-serif字体）
plt.rcParams['axes.unicode_minus'] = False  # 步骤二（解决坐标轴负数的负号显示问题）

In [ ]:
#plt画图保存
for i in list_a:
    plt.figure(i) #这一步是创建图片，否则后面的会覆盖先前的
    sns_pic = seaborn.barplot(x = '油品名',y = i, data = oil_title_df)
    fig = sns_pic.get_figure()
    fig.savefig('E:/data/data_picture/hist{}.png'.format(i)) #保存文件

In [ ]:
#画图双y轴设置，还不是很完善
#%matplotlib notebook #这个图能缩放
import matplotlib.pyplot as plt

%matplotlib inline
%config InlineBackend.figure_format = 'svg' #画的图更清晰

plt.rcParams['font.sans-serif'] = ['SimHei'] # 步骤一（替换sans-serif字体）
plt.rcParams['axes.unicode_minus'] = False  # 步骤二（解决坐标轴负数的负号显示问题）

fig = plt.figure()

ax1 = fig.add_subplot(111) #声明添加图，# 第一张图中的第一张子图

x_axix = df_result['date']
plt.title('Result Analysis')
plt.plot(x_axix, df_result['price'], color='blue', label='oil price')
ax1.set_ylabel('oil factory price')

ax2 = ax1.twinx() #这步也是必须的
plt.plot(x_axix, df_result['close_val_yesd'], color='red', label='futures')
ax1.set_ylabel('oil futures num')

plt.legend() # 显示图例
plt.gcf().autofmt_xdate() #旋转x轴文字
#plt.xticks(x_axix, rotation = 90)

plt.xlabel('date')
#plt.ylabel('price')
plt.show()

In [ ]:
#request json解析出错时

import json

response = requests.get(url_json, headers=header, params=params).text
json_dump = json.loads(response, strict=False)
json_dump

In [ ]:
# request设置

proxy = '220.230.120.101:80'
proxies = {
    'http': 'http://' + proxy,
    'https': 'https://' + proxy
    }
 header = {
    #"HOST": "mp.weixin.qq.com",
    "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
    }
    
#登录后将cookies保存到本地的方式：本次使用selenium
cookie_items = driver.get_cookies()
post={} #定义一个空的字典，存放cookies内容
#获取到的cookies是列表形式，将cookies转成json形式并存入本地名为cookie的文本中
for cookie_item in cookie_items:
    post[cookie_item['name']] = cookie_item['value'] #存到之前设置的空字典里
cookie_str = json.dumps(post)
with open('F:/wechat_public/cookie.txt', 'w+', encoding='utf-8') as f:
    f.write(cookie_str)
print("cookies信息已保存到本地")

response = requests.get(url=url, cookies=post, headers=header, proxies=proxies) 
#如果读取本地cookies，需要json.loads处理cookie_str

In [ ]:
#selenium 传入获取的cookies，数据使用上个cell

url = 'https://www.qichacha.com/cassets_6bc4a7dd26e659c333195c1f486e86f2' #目标网址
browser = webdriver.Chrome()
url_l= 'https://www.qichacha.com/user_login' #这一步特别重要，必须先打开一个目标网址对应的界面
browser.get(url_l) 
for cookie_item in cookie_items:
    #print({'name': cookie_item, 'value': cookies[cookie_item]})
    browser.add_cookie(cookie_item)
browser.get(url)

In [ ]:
#传入参数设置。一般用于获取json格式数据
#原始网址：
'https://gupiao.baidu.com/api/rails/stockbasicbatch?from=pc&os_ver=1&cuid=xxx&vv=100&format=json&stock_code=sh000001%2Cus.DJI%2CusNDAQ%2Csz399001%2Cus.IXIC%2CusOIL&timestamp=1534816667757'
#设置如下：
url = 'https://gupiao.baidu.com/api/rails/stockbasicbatch' #注意与原始网址问号位置的关系
params = {
        "from" : 'pc', 
        "osver" : '1',
        "cuid" : 'xxx',
        "vv" : "100",
        "format" : "json", 
        "stock_code" : 'sh000001', #指数代码
        "timestamp" : str(timestamp) #时间戳
        }
data_ori = requests.get(url, params = params).json()

In [ ]:
#列表去重，这个可以用于元素是字符，如果是数字还可以用list(set(li))方法
li=[1,2,3,4,5,1,2,3]
news_ids = []
for id in ids:
    if id not in news_ids:
        news_ids.append(id)
print news_ids

In [ ]:
import datetime
#python时间的操作，增加/减少整天
now=datetime.datetime.now()
delta=datetime.timedelta(days=1) #递增的时间
endnow=now+datetime.timedelta(days=6) #六天后的时间
endnow=str(endnow.strftime('%Y-%m-%d')) #六天后的时间转换成字符串
 
offset = now
 
#当日期增加到六天后的日期，循环结束
while str(offset.strftime('%Y-%m-%d')) != endnow:
    offset += delta
    print(str(offset.strftime('%Y-%m-%d')))

#字符串转换为时间格式    
from datetime import datetime
cday = datetime.strptime('2018-6-1 18:19:59', '%Y-%m-%d %H:%M:%S')

In [1]:
#日期按月加减
# pip install python-dateutil
import datetime
from dateutil.relativedelta import relativedelta 

datetime_now = datetime.datetime.now()
datetime_three_month_ago = datetime_now - relativedelta(months=3)
print (datetime_three_month_ago)

2018-06-28 10:41:55.056005


In [2]:
#两个时间相差多少天
import datetime

a = datetime.datetime(2018, 5, 20)
b = datetime.datetime(2018, 5, 19)
(a-b).days

1

In [ ]:
#调用父类方法
from datetime import datetime

class Get_economy(object):
    def __init__(self, name):
        self.name = name
        
    def get_time(self):
        now = datetime.now()
        time = now.strftime('%Y-%m-%d')
        return time
    
class Dollar(Get_economy):
    
    def __init__(self, name): #注意写法，要不就干脆不要写__init__函数，直接能继承父类参数
        super().__init__(name) #这样写能继承全部父类默认参数
        
    def test(self):
        time = super().get_time() #这是继承父类方法
        print('time is',time)

tx = Dollar('xxx')
tx.test()

In [ ]:
#类中变量的调用：
class HousePrice(object):
    url = 'https://restapi.amap.com/v3/place/around?parameters'
    route = r'E:\data\house_price\Dalian.xls'
    
    def __init__(self, distance):
        self.distance = distance
        
# 上述例子中，当HousePrice类中其他函数需要调用url,route，distance变量时，都需要使用self.url这种方法。区别是实例化时，distance变量需要传入类

In [ ]:
eval() #函数就是实现list、dict、tuple与str之间的转化
str() #函数把list，dict，tuple转为为字符串

In [1]:
#assert用法

assert 1 == 2, '小学生错误'

AssertionError: 小学生错误

In [ ]:
#转换大小写（首字母）
>>> string.capitalize()
'My name is dokelung'
>>> string.title()
'My Name Is Dokelung'

In [2]:
#输出26个英文字母
a= [chr(i) for i in range(97,123)]
print(a)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']


In [ ]:
#正则提取数字
pattern = re.compile(r'\d+\.\d+-\d+\.\d+') #寻找任意位数的浮点数-任意位数的浮点数范围
price = pattern.findall(list_t[i])[0]

text_tel = '133555662324 更多号码'
pattern = re.compile(r'\d+') #寻找任意长度整数
price = pattern.findall(text_tel)[0]
price

In [2]:
#正则对多个分隔符同时替换
import re

info = "10.10.25.14,here is my address: 0A;6E"
result = re.split(r'[,.;:\s]\s*', info)
result

['10', '10', '25', '14', 'here', 'is', 'my', 'address', '0A', '6E']

In [35]:
#内置多线程输入
import concurrent.futures

def fun(x,y):
    return x*y
    print('看我',x)


def multi_thread():
    with concurrent.futures.ThreadPoolExecutor(44) as executor: 
        df_list = list(range(0,1000))
        df_y = list(range(10))
        #print(type(df_list))
        for x,y, result in zip(df_list, df_y, executor.map(fun, df_list)):
            print('目前：',result)
            
def multi_process(): 
    '''with concurrent.futures.ProcessPoolExecutor() as executor:  #这个是多进程，很难搞，经常被莫名其妙进程占用
        df_list = list(range(0,1000))
        #print(type(df_list))
        for i, result in zip(df_list, executor.map(fun, df_list)):
            print('目前x：',i)'''
    pool = concurrent.futures.ProcessPoolExecutor()
    df_list = list(range(0,1000))
    for i in df_list:
        result = pool.submit(fun(i),i)
        print(result)

if __name__ == "__main__":
    multi_process()
    #multi_thread()

<Future at 0x1bba1f0c080 state=running>
<Future at 0x1bba1c4e1d0 state=pending>
<Future at 0x1bba1c4e3c8 state=pending>
<Future at 0x1bba1c4e9b0 state=pending>
<Future at 0x1bba1c4ea90 state=pending>
<Future at 0x1bba1c4e588 state=pending>
<Future at 0x1bba1c4eb00 state=pending>
<Future at 0x1bba1c4ea20 state=pending>
<Future at 0x1bba1c4ecf8 state=pending>
<Future at 0x1bba1c4e438 state=pending>
<Future at 0x1bba1c4e630 state=pending>
<Future at 0x1bba1c4efd0 state=pending>
<Future at 0x1bba1c4e2e8 state=pending>
<Future at 0x1bba1c4ef98 state=pending>
<Future at 0x1bba1c4e550 state=pending>
<Future at 0x1bba1da8a90 state=pending>
<Future at 0x1bba1da8da0 state=pending>
<Future at 0x1bba1da8748 state=pending>
<Future at 0x1bba1da8710 state=pending>
<Future at 0x1bba1da8b70 state=pending>
<Future at 0x1bba1da8470 state=pending>
<Future at 0x1bba1da8898 state=pending>
<Future at 0x1bba1da8be0 state=pending>
<Future at 0x1bba1da8cf8 state=pending>
<Future at 0x1bba1da85f8 state=pending>


<Future at 0x1bba1c4e1d0 state=pending>
<Future at 0x1bba1c4ea20 state=pending>
<Future at 0x1bba1c4ea58 state=pending>
<Future at 0x1bba1da8e48 state=pending>
<Future at 0x1bba28caf60 state=pending>
<Future at 0x1bba28cad30 state=pending>
<Future at 0x1bba28ca240 state=pending>
<Future at 0x1bba28ca4a8 state=pending>
<Future at 0x1bba28a4cc0 state=pending>
<Future at 0x1bba28a4d30 state=pending>
<Future at 0x1bba274b860 state=pending>
<Future at 0x1bba274bba8 state=pending>
<Future at 0x1bba274ba90 state=pending>
<Future at 0x1bba23d4860 state=pending>
<Future at 0x1bba23d4400 state=pending>
<Future at 0x1bba23d46a0 state=pending>
<Future at 0x1bba23d49b0 state=pending>
<Future at 0x1bba23c6f60 state=pending>
<Future at 0x1bba23c6828 state=pending>
<Future at 0x1bba23c6780 state=pending>
<Future at 0x1bba23c6b70 state=pending>
<Future at 0x1bba21ea7b8 state=pending>
<Future at 0x1bba21ea470 state=pending>
<Future at 0x1bba21ea2b0 state=pending>
<Future at 0x1bba21ca780 state=pending>


In [8]:
#reshape的用法
import numpy as np
z = np.array([[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12]]) #3*4
print(z.shape)
normal = z.reshape(6,2) #通常用法，但是要想好行列匹配
print(normal,'\n')
x0 = z.reshape(z.shape[0],-1) #第二个参数为-1时，根据前一个参数转换维度
print(x0)
x1 = z.reshape(z.shape[1],-1) 
print(x1)

(3, 4)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
from DBUtils.PooledDB import PooledDB
import pymysql

_dbservice_pool = None

class MysqlPool(object): #设置数据库连接池和初始化    
    """
        MYSQL数据库对象，负责产生数据库连接 , 此类中的连接采用连接池实现
        获取连接对象：conn = Mysql.get_connection()
        释放连接对象;conn.close()或del conn
    """
    
    def __init__(self,mincached=5, maxcached=14,
                maxconnections=244, blocking=True, maxshared=0):
        """
            生成MySQL数据库连接池
        :param mincached: 最少的空闲连接数，如果空闲连接数小于这个数，pool会创建一个新的连接
        :param maxcached: 最大的空闲连接数，如果空闲连接数大于这个数，pool会关闭空闲连接
        :param maxconnections: 最大的连接数
        :param blocking: 当连接数达到最大的连接数时，在请求连接的时候，如果这个值是True，请求连接的程序会一直等待，
                          直到当前连接数小于最大连接数，如果这个值是False，会报错，
        :param maxshared: 当连接数达到这个数，新请求的连接会分享已经分配出去的连接
        """        
        db_config = {
            "host": '47.92.25.70',
            "port": 3306,
            "user": 'root',
            "passwd": 'Wfn031641',
            "db": 'zhaoshang',
            "charset": 'utf8'
        }
        self.pool = PooledDB(pymysql, mincached=mincached, maxcached=maxcached, maxconnections=maxconnections,
                             blocking=blocking, maxshared=maxshared, **db_config)

    def get_connection(self):
        return self.pool.connection()

    def close(self):
        self.pool.close()

    def __del__(self):
        self.close()

# 获取mysql数据库服务器的连接
def get_dbservice_mysql_conn(): #实例化连接池类，方便调用
    """
    :return: Object  MySQL Connection
    """
    global _dbservice_pool
    if not _dbservice_pool or not isinstance(_dbservice_pool, MysqlPool):
        _dbservice_pool = MysqlPool()
    return _dbservice_pool.get_connection()

connection = get_dbservice_mysql_conn()

In [8]:
#装饰器练习

def deco(func): #传入的func参数是函数名，在wrapper里调用
    def wrapper(*args, **kwargs):
        print('call %s():' % func.__name__)
        print('args = {}'.format(*args))
        return func(*args, **kwargs) #返回的是函数名
    return wrapper #返回的是装饰器函数名

@deco  #注意装饰器行要在函数定义时def上
def func(text):
    print("I'm", text)
    
text = "python decorator"

#func(text)

def log_with_param(text): #如果要让装饰器有参数，要用3层def函数定义装饰器
    def decorator(func):
        def wrapper(*args, **kwargs):
            print('call %s():' % func.__name__)
            print('args = {}'.format(*args))
            print('decorator_param = {}'.format(text))
            return func(*args, **kwargs)

        return wrapper

    return decorator
    
@log_with_param("deco_param") #装饰器参数
def test_with_param(p):
    print(test_with_param.__name__)
    print("I'm test function's", p)
    
test_with_param(text)

call test_with_param():
args = python decorator
decorator_param = deco_param
wrapper
I'm test function's python decorator


In [22]:
l = [1,2]
t=tuple(l)
s = str(t)
print(type(s))
print(s)

<class 'str'>
(1, 2)


In [16]:
d={'a':1, 'b':2}

d.get('c','3') #如果没有，值为3，但是不改动原字典

{'a': 1, 'b': 2}

In [2]:
int('2019-11-27'.translate(str.maketrans('', '', '-')))-1

20191126